"""empty message

Revision ID: 19e3c7b51037
Revises: c39688c0f774
Create Date: 2017-03-04 19:54:16.241143

"""
from alembic import op
import sqlalchemy as sa

import geoalchemy2


# revision identifiers, used by Alembic.
revision = '19e3c7b51037'
down_revision = 'c39688c0f774'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('races', sa.Column('start_point', geoalchemy2.types.Geometry(geometry_type='POINT'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('races', 'start_point')
    # ### end Alembic commands ###
