"""empty message

Revision ID: 8d62dbc19154
Revises: 19e3c7b51037
Create Date: 2017-03-04 20:18:51.833788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d62dbc19154'
down_revision = '19e3c7b51037'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('routes', sa.Column('race_id', sa.Integer(), nullable=True))
    op.drop_constraint('routes_route_id_fkey', 'routes', type_='foreignkey')
    op.create_foreign_key(None, 'routes', 'races', ['race_id'], ['id'])
    op.drop_column('routes', 'route_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('routes', sa.Column('route_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'routes', type_='foreignkey')
    op.create_foreign_key('routes_route_id_fkey', 'routes', 'routes', ['route_id'], ['id'])
    op.drop_column('routes', 'race_id')
    # ### end Alembic commands ###
