"""empty message

Revision ID: c39688c0f774
Revises: c2bf1ecb7a78
Create Date: 2017-03-04 19:27:41.659550

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'c39688c0f774'
down_revision = 'c2bf1ecb7a78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('routes', sa.Column('geom', geoalchemy2.types.Geometry(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('routes', 'geom')
    # ### end Alembic commands ###
